import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  scrollContent: {
    padding: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    fontSize: 18,
    color: '#666',
  },
  header: {
    alignItems: 'center',
    marginBottom: 30,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  // Developer Settings Container
  devSettingsContainer: {
    backgroundColor: '#fff9e6',
    borderWidth: 2,
    borderColor: '#ffc107',
    borderRadius: 12,
    marginBottom: 24,
    overflow: 'hidden',
  },
  devSettingsHeader: {
    backgroundColor: '#fff3cd',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#ffc107',
  },
  devSettingsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#856404',
    marginBottom: 2,
  },
  devSettingsSubtitle: {
    fontSize: 12,
    color: '#997404',
    fontStyle: 'italic',
  },
  devSettingsContent: {
    padding: 16,
  },
  devSection: {
    marginTop: 16,
  },
  devSectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 12,
    color: '#856404',
  },
  mockInfo: {
    backgroundColor: '#e3f2fd',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  mockInfoText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0d47a1',
  },
  statusBar: {
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 30,
  },
  statusPremium: {
    backgroundColor: '#4caf50',
  },
  statusFree: {
    backgroundColor: '#9e9e9e',
  },
  statusText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
  },
  errorContainer: {
    backgroundColor: '#ffebee',
    padding: 16,
    borderRadius: 8,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: '#c62828',
  },
  errorText: {
    color: '#c62828',
  },
  section: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 15,
    color: '#555',
    paddingLeft: 5,
  },
  recipeCard: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
  },
  recipeCardLocked: {
    opacity: 0.7,
    backgroundColor: '#f5f5f5',
  },
  recipeTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 6,
    flexDirection: 'row',
    alignItems: 'center',
  },
  lockIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  recipeDescription: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  detailView: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 24,
    margin: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  detailTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    marginTop: 0,
    marginBottom: 16,
    color: '#333',
  },
  detailDescription: {
    fontSize: 16,
    lineHeight: 24,
    color: '#555',
    marginBottom: 24,
  },
  backButton: {
    backgroundColor: '#007bff',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 6,
    alignItems: 'center',
  },
  backButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  // Purchase Screen styles
  purchaseSubtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
  },
  productCard: {
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: '#007bff',
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  productInfo: {
    flex: 1,
    marginRight: 16,
  },
  productTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 6,
  },
  productDescription: {
    fontSize: 14,
    color: '#666',
    lineHeight: 18,
  },
  productPrice: {
    alignItems: 'flex-end',
  },
  priceAmount: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#007bff',
  },
  pricePeriod: {
    fontSize: 12,
    color: '#999',
    marginTop: 2,
  },
  purchaseActions: {
    marginTop: 20,
  },
  closeButton: {
    backgroundColor: '#e0e0e0',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#666',
    fontSize: 16,
    fontWeight: '600',
  },
  emptyText: {
    fontSize: 16,
    color: '#999',
    textAlign: 'center',
    marginVertical: 20,
  },
  // UI Mode Selector styles
  uiModeContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  uiModeButton: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  uiModeButtonActive: {
    backgroundColor: '#e3f2fd',
    borderColor: '#007bff',
  },
  uiModeButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#666',
    textAlign: 'center',
  },
  uiModeButtonTextActive: {
    color: '#007bff',
  },
  uiModeDescription: {
    fontSize: 13,
    color: '#888',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  // Adapty UI Info styles
  adaptyUIInfo: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    marginVertical: 20,
    marginHorizontal: 12,
    maxWidth: 600,
    width: '100%',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  adaptyUIInfoTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 16,
    textAlign: 'center',
  },
  adaptyUIInfoText: {
    fontSize: 16,
    color: '#555',
    lineHeight: 24,
    marginBottom: 12,
    textAlign: 'center',
  },
  adaptyUIInfoNote: {
    fontSize: 14,
    color: '#007bff',
    lineHeight: 22,
    marginTop: 8,
    padding: 12,
    backgroundColor: '#e3f2fd',
    borderRadius: 8,
    textAlign: 'center',
  },
});

