name: 💫 Feature request
description: Request a new feature
labels: ["enhancement"]
assignees:
  - divanc
body:
- type: markdown
  attributes:
    value: |
      Want event more? Request a feature, that you think would benefit this SDK
- type: textarea
  id: what-happened
  attributes:
    label: Description
    description: |
      Provide a clear description of a feature. Add expected usage scenarios
    placeholder: What is it you desire?
  validations:
    required: true
