#!/bin/bash

# Script updates the version number in the CrossplatformVersion.plist file
# so that native iOS code can access version from package.json

set -e

PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
PLIST_FILE=./lib/ios/CrossplatformVersion.plist

/usr/libexec/PlistBuddy -c "Set :version $PACKAGE_VERSION" "$PLIST_FILE"

echo "<!-- THIS FILE IS GENERATED BY /scripts/update_ios_version.sh SCRIPT. DO NOT EDIT MANUALLY -->" >> "$PLIST_FILE"

echo "$PLIST_FILE --> $PACKAGE_VERSION"